vich_uploader:
    db_driver: orm

    mappings:
        document_proof:
            uri_prefix: /uploads/proofs
            upload_destination: '%kernel.project_dir%/public/uploads/proofs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        document_invoice:
            uri_prefix: /uploads/invoices
            upload_destination: '%kernel.project_dir%/public/uploads/invoices'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
